service: xana-image-resizing-python

provider:
  name: aws
  stackName: dev-xana-dynamic-image-resize
  region: us-east-1
  iam:
    role: arn:aws:iam::845847047647:role/mohneesh-transcoder-role-for-lambda
  environment:
    ACCESS_KEY_ID: AKIA4J4DJVXPY3ZJFXNS
    ACCESS_SECRET: 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

package:
  excludeDevDependencies: true
  exclude:
    - "node_modules/"
    - "*.json"
    - "requirements.txt"
    - "*.md"
    - "setup.cfg"

functions:
  resize:
    handler: handler.call
    name: xana-image-resizing-python-resize
    description: A pillow based lambda for resizing images dynamically
    runtime: python3.8
    timeout: 10
    memorySize: 1836
    environment:
      BUCKET: api-test-xana
      REGION: us-east-1
    layers:
      - arn:aws:lambda:us-east-1:845847047647:layer:pillow:1
    events:
      - http:
          path: /{size}/{image}
          method: get

  resize-v2:
    handler: handler_v2.main
    name: xana-image-resizing-python-resize-v2
    description: v2 of A pillow based lambda for resizing images dynamically
    runtime: python3.8
    timeout: 10
    memorySize: 1836
    environment:
      BUCKET: api-test-xana
      REGION: us-east-1
    layers:
      - arn:aws:lambda:us-east-1:845847047647:layer:libvips:1
    events:
      - http:
          # path: /{size}/{image}
          path: /compress/{image}
          method: get
# plugins:
#   - serverless-s3-local
#   - serverless-offline
#   - serverless-python-requirements

